### ISSUE TITLE
Adding a rock paper scissors game

### ISSUE THREAD

**Issue by govkartha** [virejdasani/Alexis#31]
**Is your feature request related to a problem? Please describe.**
I would like to add a rock paper scissors game apart from the tictactoe game available right now.

**Describe the solution you'd like**
Add a new game.

**Comment by virejdasani** [comment]
Sounds good, go for it!

**Comment by govkartha** [comment]
Done!

**Comment by sirKiraUzumaki** [comment]
Bro I opened the PR before this issue and this guy got his PR merged and I got my PR closed stating it already exist... bro I was the first one to open the PR.. like wtf

**Comment by virejdasani** [comment]
@sirKiraUzumaki sorry about that, I'll mark yours as hacktoberfest-accepted

**Comment by sirKiraUzumaki** [comment]
Thanks
